import React, { useState, useEffect } from "react";
import { FiUsers, FiBriefcase, FiDollarSign, FiTrendingUp } from "react-icons/fi";
import { 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer 
} from "recharts";
import { motion } from "framer-motion";
import { getDashboardStats } from "../../Services/dashboardService";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";

const Dashboard = () => {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [filterType, setFilterType] = useState("Last 7 Days"); // Options: "Last 7 Days", "This Month", "This Year"

  useEffect(() => {
    const fetchStats = async () => {
      try {
        setLoading(true);
        const res = await getDashboardStats();
        setData(res.data);
      } catch (error) {
        console.error("Error fetching dashboard statistics:", error);
        toast.error("Failed to load dashboard statistics");
      } finally {
        setLoading(false);
      }
    };
    fetchStats();
  }, []);

  if (loading) {
    return <div className="p-8 text-center text-gray-600 font-medium">Loading dashboard overview...</div>;
  }

  if (!data) {
    return <div className="p-8 text-center text-red-600 font-medium">Failed to retrieve dashboard data.</div>;
  }

  // Format currency helper
  const formatCurrency = (val) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      maximumFractionDigits: 0
    }).format(val);
  };

  const stats = [
    { title: "Total Users", value: data.totalUsers.toLocaleString(), icon: FiUsers, color: "bg-blue-100 text-blue-600", path: "/home/user" },
    { title: "Total Partners", value: data.totalVendors.toLocaleString(), icon: FiBriefcase, color: "bg-[#0D877F]/20 text-[#0D877F]", path: "/home/vendor" },
    { title: "Total Earnings", value: formatCurrency(data.totalEarnings), icon: FiDollarSign, color: "bg-yellow-100 text-yellow-600" },
    { title: "Active Bookings", value: data.totalActiveBookings.toLocaleString(), icon: FiTrendingUp, color: "bg-purple-100 text-purple-600", path: "/home/booking" },
  ];

  // Resolve chart details based on select filter option
  let chartData = [];
  let dataKeyX = "day";
  let chartTitle = "Weekly Earnings";
  let chartSub = "Revenue generated over the last 7 days";

  if (filterType === "This Month") {
    chartData = data.charts.monthly;
    dataKeyX = "day";
    chartTitle = "Monthly Earnings";
    chartSub = "Revenue generated throughout this month";
  } else if (filterType === "This Year") {
    chartData = data.charts.yearly;
    dataKeyX = "month";
    chartTitle = "Yearly Earnings";
    chartSub = "Revenue generated by month this year";
  } else {
    // Default: Last 7 Days (Weekly)
    chartData = data.charts.weekly;
    dataKeyX = "day";
    chartTitle = "Weekly Earnings";
    chartSub = "Revenue generated over the last 7 days";
  }

  return (
    <div className="min-h-screen bg-gray-50 p-6 w-full">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-7xl mx-auto space-y-8"
      >
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Dashboard Overview</h1>
          <p className="text-gray-500 mt-1">Welcome back! Here's a summary of DoorHelp's performance.</p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, index) => {
            const Icon = stat.icon;
            return (
              <motion.div 
                key={index}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: index * 0.1 }}
                onClick={() => stat.path && navigate(stat.path)}
                className={`bg-white p-6 rounded-2xl shadow-sm border border-gray-100 flex items-center justify-between transition-transform hover:-translate-y-1 hover:shadow-md ${stat.path ? "cursor-pointer" : "cursor-default"}`}
              >
                <div>
                  <p className="text-sm font-medium text-gray-500 mb-1">{stat.title}</p>
                  <h3 className="text-2xl font-bold text-gray-900">{stat.value}</h3>
                </div>
                <div className={`p-4 rounded-full ${stat.color}`}>
                  <Icon size={24} />
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Chart Section */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100"
        >
          <div className="mb-6 flex justify-between items-center">
            <div>
              <h2 className="text-xl font-bold text-gray-900">{chartTitle}</h2>
              <p className="text-sm text-gray-500">{chartSub}</p>
            </div>
            <select 
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="bg-gray-50 border border-gray-200 text-gray-700 text-sm rounded-lg focus:ring-[#0D877F] focus:border-[#0D877F] block p-2 outline-none"
            >
              <option value="Last 7 Days">Last 7 Days</option>
              <option value="This Month">This Month</option>
              <option value="This Year">This Year</option>
            </select>
          </div>
          
          <div className="h-[400px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorEarnings" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#0D877F" stopOpacity={0.4}/>
                    <stop offset="95%" stopColor="#0D877F" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                <XAxis 
                  dataKey={dataKeyX} 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fill: '#6B7280', fontSize: 14 }}
                  dy={10}
                />
                <YAxis 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fill: '#6B7280', fontSize: 14 }}
                  tickFormatter={(value) => `₹${value}`}
                  dx={-10}
                />
                <Tooltip 
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)' }}
                  formatter={(value) => [`₹${value}`, "Earnings"]}
                  labelStyle={{ fontWeight: 'bold', color: '#374151', marginBottom: '4px' }}
                />
                <Area 
                  type="monotone" 
                  dataKey="earnings" 
                  stroke="#0D877F" 
                  strokeWidth={3}
                  fillOpacity={1} 
                  fill="url(#colorEarnings)" 
                  activeDot={{ r: 8, fill: "#0D877F", stroke: "#fff", strokeWidth: 3 }}
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </motion.div>
      </motion.div>
    </div>
  );
};

export default Dashboard;
